apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-auth-config
data:
  POSTGRES_DB: "auth_db"
  POSTGRES_USER: "auth_user"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "auth_pass"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-auth-config
            - secretRef:
                name: postgres-auth-secret
          volumeMounts:
            - name: postgres-auth-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-auth-storage
          persistentVolumeClaim:
            claimName: postgres-auth-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-svc        # Name referenced by SPRING_DATASOURCE_URL in auth-service
spec:
  type: ClusterIP
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432