apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_PROFILES_ACTIVE: "dev"

  SPRING_REDIS_HOST: "redis-svc"
  SPRING_REDIS_PORT: "6379"

  SERVER_FORWARD_HEADERS_STRATEGY: "framework"

  CORS_ALLOWED_ORIGINS: "http://localhost:5173"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE_SECONDS: "3600"

  GATEWAY_CLIENT_ID: "simple-wms-api-gateway"
  AUTH_SERVER_ISSUER_URL: "http://auth-service:9000"

  SUCCESS_LOGIN_REDIRECT: "http://localhost:5173/"
  POST_LOGOUT_REDIRECT_URL: "http://localhost:5173/login"

  AUTHORIZATION_URI: "http://auth.localhost/oauth2/authorize"

  USER_INFO_URI: "http://auth-service:9000/userinfo"
  JWK_SET_URI: "http://auth-service:9000/oauth2/jwks"
  TOKEN_URI: "http://auth-service:9000/oauth2/token"

  SESSION_DURATION: "7d"

---

apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
type: Opaque
stringData:
  SPRING_REDIS_PASSWORD: "redis-pass"
  GATEWAY_CLIENT_SECRET: "secret"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: api-gateway-secret

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080