apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SPRING_PROFILES_ACTIVE: "dev"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth-svc:5432/auth_db"
  SPRING_DATASOURCE_USERNAME: "auth_user"

  SERVER_FORWARD_HEADERS_STRATEGY: "framework"

  JWT_ACCESS_TOKEN_EXPIRATION_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRATION_HOURS: "12"

  AUTH_SERVER_ISSUER_URL: "http://auth-service:9000"
  AUTH_SERVER_REDIRECT_URI: "http://localhost/login/oauth2/code/simple-wms-api-gateway"
  AUTH_SERVER_POST_LOGOUT: "http://localhost:5173/"
  GATEWAY_CLIENT_ID: "simple-wms-api-gateway"

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "auth_pass"
  JWT_SECRET: "vZWtIb0AUbrMiSNB1tL+EzavlbQ9gpEgQpYxlLs1FuA"
  GATEWAY_CLIENT_SECRET: "secret"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 9000
      targetPort: 9000